'''
The Google Translate API offers many languages, the list of them can be retrieved through an API endpoint itself, however:
    1. This is slightly unstable, since we like to know the list of available languages early when defining safe types.
    2. This is slightly inefficient, since we'd have to fetch it every time, either on startup or at the earliest point we need it.
    3. Google does not include every language in this list.

What follows is the saved output of one such .get_languages() call, followed by a hand-crafted dict of 'secret' languages (at time of writing).
'''


# Output of translate_client.get_languages()
# Fetched: 2024-10-21
CANONICAL_TRANSLATE_LANGUAGES = [
    {'language': 'ab', 'name': 'Abkhaz'},
    {'language': 'ace', 'name': 'Acehnese'},
    {'language': 'ach', 'name': 'Acholi'},
    {'language': 'aa', 'name': 'Afar'},
    {'language': 'af', 'name': 'Afrikaans'},
    {'language': 'sq', 'name': 'Albanian'},
    {'language': 'alz', 'name': 'Alur'},
    {'language': 'am', 'name': 'Amharic'},
    {'language': 'ar', 'name': 'Arabic'},
    {'language': 'hy', 'name': 'Armenian'},
    {'language': 'as', 'name': 'Assamese'},
    {'language': 'av', 'name': 'Avar'},
    {'language': 'awa', 'name': 'Awadhi'},
    {'language': 'ay', 'name': 'Aymara'},
    {'language': 'az', 'name': 'Azerbaijani'},
    {'language': 'ban', 'name': 'Balinese'},
    {'language': 'bal', 'name': 'Baluchi'},
    {'language': 'bm', 'name': 'Bambara'},
    {'language': 'bci', 'name': 'Baoulé'},
    {'language': 'ba', 'name': 'Bashkir'},
    {'language': 'eu', 'name': 'Basque'},
    {'language': 'btx', 'name': 'Batak Karo'},
    {'language': 'bts', 'name': 'Batak Simalungun'},
    {'language': 'bbc', 'name': 'Batak Toba'},
    {'language': 'be', 'name': 'Belarusian'},
    {'language': 'bem', 'name': 'Bemba'},
    {'language': 'bn', 'name': 'Bengali'},
    {'language': 'bew', 'name': 'Betawi'},
    {'language': 'bho', 'name': 'Bhojpuri'},
    {'language': 'bik', 'name': 'Bikol'},
    {'language': 'bs', 'name': 'Bosnian'},
    {'language': 'br', 'name': 'Breton'},
    {'language': 'bg', 'name': 'Bulgarian'},
    {'language': 'bua', 'name': 'Buryat'},
    {'language': 'yue', 'name': 'Cantonese'},
    {'language': 'ca', 'name': 'Catalan'},
    {'language': 'ceb', 'name': 'Cebuano'},
    {'language': 'ch', 'name': 'Chamorro'},
    {'language': 'ce', 'name': 'Chechen'},
    {'language': 'ny', 'name': 'Chichewa'},
    {'language': 'zh', 'name': 'Chinese (Simplified)'},
    {'language': 'zh-TW', 'name': 'Chinese (Traditional)'},
    {'language': 'chk', 'name': 'Chuukese'},
    {'language': 'cv', 'name': 'Chuvash'},
    {'language': 'co', 'name': 'Corsican'},
    {'language': 'crh', 'name': 'Crimean Tatar'},
    {'language': 'hr', 'name': 'Croatian'},
    {'language': 'cs', 'name': 'Czech'},
    {'language': 'da', 'name': 'Danish'},
    {'language': 'fa-AF', 'name': 'Dari'},
    {'language': 'din', 'name': 'Dinka'},
    {'language': 'dv', 'name': 'Divehi'},
    {'language': 'doi', 'name': 'Dogri'},
    {'language': 'dov', 'name': 'Dombe'},
    {'language': 'nl', 'name': 'Dutch'},
    {'language': 'dyu', 'name': 'Dyula'},
    {'language': 'dz', 'name': 'Dzongkha'},
    {'language': 'en', 'name': 'English'},
    {'language': 'eo', 'name': 'Esperanto'},
    {'language': 'et', 'name': 'Estonian'},
    {'language': 'ee', 'name': 'Ewe'},
    {'language': 'fo', 'name': 'Faroese'},
    {'language': 'fj', 'name': 'Fijian'},
    {'language': 'tl', 'name': 'Filipino'},
    {'language': 'fi', 'name': 'Finnish'},
    {'language': 'fon', 'name': 'Fon'},
    {'language': 'fr', 'name': 'French'},
    {'language': 'fy', 'name': 'Frisian'},
    {'language': 'fur', 'name': 'Friulian'},
    {'language': 'ff', 'name': 'Fulfulde'},
    {'language': 'gaa', 'name': 'Ga'},
    {'language': 'gl', 'name': 'Galician'},
    {'language': 'lg', 'name': 'Ganda'},
    {'language': 'ka', 'name': 'Georgian'},
    {'language': 'de', 'name': 'German'},
    {'language': 'el', 'name': 'Greek'},
    {'language': 'gn', 'name': 'Guarani'},
    {'language': 'gu', 'name': 'Gujarati'},
    {'language': 'ht', 'name': 'Haitian Creole'},
    {'language': 'cnh', 'name': 'Hakha Chin'},
    {'language': 'ha', 'name': 'Hausa'},
    {'language': 'haw', 'name': 'Hawaiian'},
    {'language': 'iw', 'name': 'Hebrew'},
    {'language': 'hil', 'name': 'Hiligaynon'},
    {'language': 'hi', 'name': 'Hindi'},
    {'language': 'hmn', 'name': 'Hmong'},
    {'language': 'hu', 'name': 'Hungarian'},
    {'language': 'hrx', 'name': 'Hunsrik'},
    {'language': 'iba', 'name': 'Iban'},
    {'language': 'is', 'name': 'Icelandic'},
    {'language': 'ig', 'name': 'Igbo'},
    {'language': 'ilo', 'name': 'Iloko'},
    {'language': 'id', 'name': 'Indonesian'},
    {'language': 'ga', 'name': 'Irish Gaelic'},
    {'language': 'it', 'name': 'Italian'},
    {'language': 'jam', 'name': 'Jamaican Patois'},
    {'language': 'ja', 'name': 'Japanese'},
    {'language': 'jw', 'name': 'Javanese'},
    {'language': 'kac', 'name': 'Jingpo'},
    {'language': 'kl', 'name': 'Kalaallisut'},
    {'language': 'kn', 'name': 'Kannada'},
    {'language': 'kr', 'name': 'Kanuri'},
    {'language': 'pam', 'name': 'Kapampangan'},
    {'language': 'kk', 'name': 'Kazakh'},
    {'language': 'kha', 'name': 'Khasi'},
    {'language': 'km', 'name': 'Khmer'},
    {'language': 'cgg', 'name': 'Kiga'},
    {'language': 'kg', 'name': 'Kikongo'},
    {'language': 'rw', 'name': 'Kinyarwanda'},
    {'language': 'ktu', 'name': 'Kituba'},
    {'language': 'trp', 'name': 'Kokborok'},
    {'language': 'kv', 'name': 'Komi'},
    {'language': 'gom', 'name': 'Konkani'},
    {'language': 'ko', 'name': 'Korean'},
    {'language': 'kri', 'name': 'Krio'},
    {'language': 'ku', 'name': 'Kurdish (Kurmanji)'},
    {'language': 'ckb', 'name': 'Kurdish (Sorani)'},
    {'language': 'ky', 'name': 'Kyrgyz'},
    {'language': 'lo', 'name': 'Lao'},
    {'language': 'ltg', 'name': 'Latgalian'},
    {'language': 'la', 'name': 'Latin'},
    {'language': 'lv', 'name': 'Latvian'},
    {'language': 'lij', 'name': 'Ligurian'},
    {'language': 'li', 'name': 'Limburgan'},
    {'language': 'ln', 'name': 'Lingala'},
    {'language': 'lt', 'name': 'Lithuanian'},
    {'language': 'lmo', 'name': 'Lombard'},
    {'language': 'luo', 'name': 'Luo'},
    {'language': 'lb', 'name': 'Luxembourgish'},
    {'language': 'mk', 'name': 'Macedonian'},
    {'language': 'mad', 'name': 'Madurese'},
    {'language': 'mai', 'name': 'Maithili'},
    {'language': 'mak', 'name': 'Makassar'},
    {'language': 'mg', 'name': 'Malagasy'},
    {'language': 'ms', 'name': 'Malay'},
    {'language': 'ms-Arab', 'name': 'Malay (Jawi)'},
    {'language': 'ml', 'name': 'Malayalam'},
    {'language': 'mt', 'name': 'Maltese'},
    {'language': 'mam', 'name': 'Mam'},
    {'language': 'gv', 'name': 'Manx'},
    {'language': 'mi', 'name': 'Maori'},
    {'language': 'mr', 'name': 'Marathi'},
    {'language': 'mh', 'name': 'Marshallese'},
    {'language': 'mwr', 'name': 'Marwadi'},
    {'language': 'mfe', 'name': 'Mauritian Creole'},
    {'language': 'chm', 'name': 'Meadow Mari'},
    {'language': 'mni-Mtei', 'name': 'Meiteilon (Manipuri)'},
    {'language': 'min', 'name': 'Minang'},
    {'language': 'lus', 'name': 'Mizo'},
    {'language': 'mn', 'name': 'Mongolian'},
    {'language': 'my', 'name': 'Myanmar (Burmese)'},
    {'language': 'nhe', 'name': 'Nahuatl (Eastern Huasteca)'},
    {'language': 'ndc-ZW', 'name': 'Ndau'},
    {'language': 'nr', 'name': 'Ndebele (South)'},
    {'language': 'new', 'name': 'Nepalbhasa (Newari)'},
    {'language': 'ne', 'name': 'Nepali'},
    {'language': 'bm-Nkoo', 'name': 'NKo'},
    {'language': 'nso', 'name': 'Northern Sotho'},
    {'language': 'no', 'name': 'Norwegian'},
    {'language': 'nus', 'name': 'Nuer'},
    {'language': 'oc', 'name': 'Occitan'},
    {'language': 'or', 'name': 'Odia (Oriya)'},
    {'language': 'om', 'name': 'Oromo'},
    {'language': 'os', 'name': 'Ossetian'},
    {'language': 'pag', 'name': 'Pangasinan'},
    {'language': 'pap', 'name': 'Papiamento'},
    {'language': 'ps', 'name': 'Pashto'},
    {'language': 'fa', 'name': 'Persian'},
    {'language': 'pl', 'name': 'Polish'},
    {'language': 'pt', 'name': 'Portuguese'},
    {'language': 'pt-PT', 'name': 'Portuguese (Portugal)'},
    {'language': 'pa', 'name': 'Punjabi'},
    {'language': 'pa-Arab', 'name': 'Punjabi (Shahmukhi)'},
    {'language': 'kek', 'name': 'Q\'eqchi\''},
    {'language': 'qu', 'name': 'Quechua'},
    {'language': 'rom', 'name': 'Romani'},
    {'language': 'ro', 'name': 'Romanian'},
    {'language': 'rn', 'name': 'Rundi'},
    {'language': 'ru', 'name': 'Russian'},
    {'language': 'se', 'name': 'Sami (North)'},
    {'language': 'sm', 'name': 'Samoan'},
    {'language': 'sg', 'name': 'Sango'},
    {'language': 'sa', 'name': 'Sanskrit'},
    {'language': 'sat-Latn', 'name': 'Santali'},
    {'language': 'gd', 'name': 'Scots Gaelic'},
    {'language': 'sr', 'name': 'Serbian'},
    {'language': 'st', 'name': 'Sesotho'},
    {'language': 'crs', 'name': 'Seychellois Creole'},
    {'language': 'shn', 'name': 'Shan'},
    {'language': 'sn', 'name': 'Shona'},
    {'language': 'scn', 'name': 'Sicilian'},
    {'language': 'szl', 'name': 'Silesian'},
    {'language': 'sd', 'name': 'Sindhi'},
    {'language': 'si', 'name': 'Sinhala'},
    {'language': 'sk', 'name': 'Slovak'},
    {'language': 'sl', 'name': 'Slovenian'},
    {'language': 'so', 'name': 'Somali'},
    {'language': 'es', 'name': 'Spanish'},
    {'language': 'su', 'name': 'Sundanese'},
    {'language': 'sus', 'name': 'Susu'},
    {'language': 'sw', 'name': 'Swahili'},
    {'language': 'ss', 'name': 'Swati'},
    {'language': 'sv', 'name': 'Swedish'},
    {'language': 'ty', 'name': 'Tahitian'},
    {'language': 'tg', 'name': 'Tajik'},
    {'language': 'ber-Latn', 'name': 'Tamazight'},
    {'language': 'ber', 'name': 'Tamazight (Tifinagh)'},
    {'language': 'ta', 'name': 'Tamil'},
    {'language': 'tt', 'name': 'Tatar'},
    {'language': 'te', 'name': 'Telugu'},
    {'language': 'tet', 'name': 'Tetum'},
    {'language': 'th', 'name': 'Thai'},
    {'language': 'bo', 'name': 'Tibetan'},
    {'language': 'ti', 'name': 'Tigrinya'},
    {'language': 'tiv', 'name': 'Tiv'},
    {'language': 'tpi', 'name': 'Tok Pisin'},
    {'language': 'to', 'name': 'Tongan'},
    {'language': 'ts', 'name': 'Tsonga'},
    {'language': 'tn', 'name': 'Tswana'},
    {'language': 'tcy', 'name': 'Tulu'},
    {'language': 'tum', 'name': 'Tumbuka'},
    {'language': 'tr', 'name': 'Turkish'},
    {'language': 'tk', 'name': 'Turkmen'},
    {'language': 'tyv', 'name': 'Tuvan'},
    {'language': 'ak', 'name': 'Twi'},
    {'language': 'udm', 'name': 'Udmurt'},
    {'language': 'uk', 'name': 'Ukrainian'},
    {'language': 'ur', 'name': 'Urdu'},
    {'language': 'ug', 'name': 'Uyghur'},
    {'language': 'uz', 'name': 'Uzbek'},
    {'language': 've', 'name': 'Venda'},
    {'language': 'vec', 'name': 'Venetian'},
    {'language': 'vi', 'name': 'Vietnamese'},
    {'language': 'war', 'name': 'Waray'},
    {'language': 'cy', 'name': 'Welsh'},
    {'language': 'wo', 'name': 'Wolof'},
    {'language': 'xh', 'name': 'Xhosa'},
    {'language': 'sah', 'name': 'Yakut'},
    {'language': 'yi', 'name': 'Yiddish'},
    {'language': 'yo', 'name': 'Yoruba'},
    {'language': 'yua', 'name': 'Yucatec Maya'},
    {'language': 'zap', 'name': 'Zapotec'},
    {'language': 'zu', 'name': 'Zulu'},
    {'language': 'he', 'name': 'Hebrew'},
    {'language': 'jv', 'name': 'Javanese'},
    {'language': 'zh-CN', 'name': 'Chinese (Simplified)'},
]


# Languages not mentioned by the API
SECRET_TRANSLATE_LANGUAGES = [
    {'language': 'fr-CA', 'name': 'French (Canadian)'},
    {'language': 'iu', 'name': 'Inuktut'},
    {'language': 'iu-Latn', 'name': 'Inuktut (Latin)'},
    {'language': 'lua', 'name': 'Tshiluba'},
    {'language': 'crh-Latn', 'name': 'Crimean Tatar (Latin)'},
    {'language': 'sat', 'name': 'Santali (Ol Chiki)'},
]


ALL_TRANSLATE_LANGUAGES = SECRET_TRANSLATE_LANGUAGES + CANONICAL_TRANSLATE_LANGUAGES


LANGUAGES_BY_CODE_LOWER = dict()
LANGUAGES_BY_NAME_LOWER = dict()

for language in ALL_TRANSLATE_LANGUAGES:
    code = language['language'].lower()
    name = language['name'].lower()
    LANGUAGES_BY_CODE_LOWER[code] = language
    LANGUAGES_BY_NAME_LOWER[name] = language
    if ' (' in name:
        # Allow 'Chinese' as an alias for 'Chinese (Simplified)'
        #   but avoid 'French (Canadian)' shadowing 'French'
        root_name = name[:name.index(' (')]
        if root_name not in LANGUAGES_BY_NAME_LOWER:
            LANGUAGES_BY_NAME_LOWER[root_name] = language

ALL_LANGUAGE_KEYS = set(LANGUAGES_BY_CODE_LOWER) | set(LANGUAGES_BY_NAME_LOWER)

def get_language(code_or_name: str) -> dict[str, str] | None:
    '''
    Get a language record ({'language': 'en', 'name': 'English'}) by either its code or name.
    '''
    code_or_name = code_or_name.lower()
    return LANGUAGES_BY_CODE_LOWER.get(code_or_name) or LANGUAGES_BY_NAME_LOWER.get(code_or_name)
